server:
  port: 8887
#spring:
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 1234
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update